// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTypesenseCollection() {
  return window['go']['main']['App']['CreateTypesenseCollection']();
}

export function GetFileContent(arg1) {
  return window['go']['main']['App']['GetFileContent'](arg1);
}

export function GetPort() {
  return window['go']['main']['App']['GetPort']();
}

export function IndexFolder(arg1) {
  return window['go']['main']['App']['IndexFolder'](arg1);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveFileContent'](arg1, arg2);
}
