// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTypesenseCollection():Promise<string>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetPort():Promise<number>;

export function IndexFolder(arg1:string):Promise<string>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;
